import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import { Rubik, Nunito_Sans, Montserrat } from "next/font/google";
import style from "@/app/app.module.scss";
import StatusBarPage from "@/app/_components/StatusBar";
import Loading from "@/components/Loading/Loading";
import AppShell from "@/app/AppShell";
const rubik = Rubik({ subsets: ["latin"], weight: ["400", "600", "700"], variable: "--font-rubik" });
const nunito = Nunito_Sans({ subsets: ["latin"], weight: ["400", "600"], variable: "--font-nunito" });
const montserrat = Montserrat({ subsets: ["latin"], weight: ["600"], variable: "--font-montserrat" });
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${rubik.variable} ${nunito.variable} ${montserrat.variable}`}>
        <div className={style.statusBarContainer}>
          <StatusBarPage />
        </div>
        <div className={style.loadingContainer}>
          <Loading />
        </div>
          <AppShell>
            {children}
          </AppShell>
      </body>
    </html>
  );
}
